{
  parserClass="org.thymeleaf.extras.idea.lang.fragment.selection.parser.FragmentSelectorParser"
  parserUtilClass="org.thymeleaf.extras.idea.lang.fragment.selection.parser.FragmentSelectorParserUtil"

  psiPackage="org.thymeleaf.extras.idea.lang.fragment.selection.psi"
  psiImplPackage="org.thymeleaf.extras.idea.lang.fragment.selection.psi.impl"
  // psiImplUtilClass="org.thymeleaf.extras.idea.lang.fragment.selection.psi.impl.FragmentSelectionPsiImplUtil"

  elementTypeHolderClass="org.thymeleaf.extras.idea.lang.fragment.selection.parser.FragmentSelectorElementTypes"
  elementTypeClass="org.thymeleaf.extras.idea.lang.fragment.selection.parser.FragmentSelectorCompositeElementType"
  tokenTypeClass="org.thymeleaf.extras.idea.lang.fragment.selection.parser.FragmentSelectorElementType"

  implements="org.thymeleaf.extras.idea.lang.fragment.selection.psi.FragmentSelectorPsiCompositeElement"
  extends="org.thymeleaf.extras.idea.lang.fragment.selection.psi.impl.FragmentSelectorPsiCompositeElementImpl"

  tokens=[
    OPERATOR='::'
    OPEN_PARENS='('
    CLOSE_PARENS=')'
    OPEN_ARRAY='['
    CLOSE_ARRAY=']'
    COMMA=','

    string='regexp:([^ \n:(),]+)'
  ]


  mixin("dom_selector")="org.thymeleaf.extras.idea.lang.fragment.selection.psi.impl.DomSelectorImplMixin"
  mixin("template_name")="org.thymeleaf.extras.idea.lang.fragment.selection.psi.impl.TemplateNameImplMixin"
  // implements("dom_selector|template_name")=["com.intellij.psi.ContributedReferenceHost" "org.thymeleaf.extras.idea.lang.fragment.selection.psi.FragmentSelectorPsiCompositeElement"]

  name("dom_selector")='Selector or name'
  name("template_name")='Name'

  name(".*expr")='expression'
  name(".*expression")='expression'
}

root ::= fragment_selection_expression

fragment_selection_expression ::=  fragment_spec [fragment_arguments] {
    methods=[
        template_name="fragment_spec/template_name"
        dom_selector="fragment_spec/dom_selector"
    ]
}

private fragment_spec ::= (template_name ['::' dom_selector]) | ('::' dom_selector)
template_name         ::= string
dom_selector          ::= string

fragment_argument_list ::= '(' fragment_argument_list ')' {pin=1}
fragment_arguments     ::= fragment_argument (',' fragment_argument)*  {pin(".*")=1}
fragment_argument      ::= string {recoverUntil}

record_tuple ::= '{' record_fields? '}' {pin=1}
record_fields ::= record_field (',' record_field)* {pin(".*")=1}
record_field ::= (q_atom | '_') '=' (qualified_atom_expression | expression) {
  pin=1
  methods = [
    getReference
    field_name_atom = "q_atom[0]"
  ]
  recoverUntil="tuple_recoverer"
}